local ls = require("luasnip")
local c = ls.choice_node
local i = ls.insert_node
local rep = require("luasnip.extras").rep
local s = ls.snippet
local sn = ls.snippet_node
local t = ls.text_node

function _G.calculate_csharp_namespace()
  local path = vim.fn.expand("%:p:h")
  local project_root = "path/to/your/project"
  local path_relative = path:sub(#project_root + 2)
  local namespace = path_relative:gsub("[/\\]", ".")
  return namespace
end

ls.snippets = {
  csharp = {
    ls.parser.parse_snippet(
      "nsp",
      "namespace " .. _G.calculate_csharp_namespace() .. "\n{\n    $0\n}"
    ),
  },
  typescript = {
    s("anf", {
      t("("),
      i(1, "args"),
      t(") => "),
      i(0),
    }, { description = "Creates an arrow function" }),
    s("genf", {
      t("function "),
      i(1, "functionName"),
      t("<"),
      i(2, "T"),
      t(">("),
      i(3, "params: "),
      rep(2),
      t("): "),
      rep(2),
      t(" {"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates a generic function" }),
    s("typeguard", {
      t("function is"),
      i(1, "Type"),
      t("("),
      i(2, "obj"),
      t(": any): obj is "),
      rep(1),
      t(" {"),
      t({ "", "\treturn " }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates a type guard function" }),
    s("decorator", {
      t("@"),
      i(1, "DecoratorName"),
      t("("),
      i(2, "params"),
      t(")"),
      t({ "", "" }),
      i(0),
    }, { description = "Applies a decorator to a class or method" }),
    s("mapped", {
      t("type "),
      i(1, "NewType"),
      t(" = {"),
      t({ "", "\t[Key in keyof " }),
      i(2, "ExistingType"),
      t("]: "),
      i(3, "Type"),
      t({ "", "};" }),
    }, { description = "Creates a mapped type" }),
    s("condtype", {
      t("type "),
      i(1, "TypeName"),
      t(" = "),
      i(2, "Condition"),
      t(" extends "),
      i(3, "OtherType"),
      t(" ? "),
      i(4, "TrueType"),
      t(" : "),
      i(5, "FalseType"),
      t(";"),
    }, { description = "Defines a conditional type" }),
    s("moduleaug", {
      t("declare module '"),
      i(1, "moduleName"),
      t("' {"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Performs module augmentation" }),
    s("idxintf", {
      t("interface "),
      i(1, "InterfaceName"),
      t(" {"),
      t({ "", "\t[key: " }),
      i(2, "KeyType"),
      t("]: "),
      i(3, "ValueType"),
      t(";"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates an interface with an index signature" }),
    s("curry", {
      t("const "),
      i(1, "curriedFunc"),
      t(" = ("),
      i(2, "param1: "),
      i(3, "Type1"),
      t(") => ("),
      i(4, "param2: "),
      i(5, "Type2"),
      t(") => "),
      i(0),
    }, { description = "Creates a curried function" }),
    s("hook", {
      t("function use"),
      i(1, "HookName"),
      t("() {"),
      t({ "", "\tconst [state, setState] = React.useState(" }),
      i(2, "initialState"),
      t(");"),
      t({ "", "\t" }),
      i(0),
      t({ "", "\treturn state;" }),
      t({ "", "}" }),
    }, { description = "Defines a custom React hook" }),
    s("union", {
      t("type "),
      i(1, "UnionName"),
      t(" = "),
      i(2, "Type1"),
      t(" | "),
      i(3, "Type2"),
      t(";"),
    }, { description = "Creates a union type" }),
    s("enum", {
      t("enum "),
      i(1, "EnumName"),
      t(" {"),
      t({ "", "\t" }),
      i(2, "Member1"),
      t(" = "),
      i(3, "Value1"),
      t(","),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Declares an enum" }),
    s("symbol", {
      t("const "),
      i(1, "sym"),
      t(" = Symbol('"),
      i(2, "description"),
      t("');"),
    }, { description = "Creates a unique symbol" }),
    s("tmpltype", {
      t("type "),
      i(1, "TypeName"),
      t(" = `"),
      i(2, "Prefix${"),
      i(3, "TypeVar"),
      t("}Suffix`"),
      t(";"),
    }, { description = "Defines a template literal type" }),
    s("keyremap", {
      t("type "),
      i(1, "RemappedType"),
      t(" = {"),
      t({ "", "\t[Key in keyof " }),
      i(2, "OriginalType"),
      t(" as "),
      i(3, "NewKey<Key>"),
      t("]: "),
      i(4, "ValueType"),
      t({ "", "};" }),
    }, { description = "Remaps keys in a mapped type" }),
    s("infer", {
      t("type "),
      i(1, "ReturnType"),
      t("<T> = T extends ("),
      i(2, "args"),
      t(") => infer R ? R : any;"),
    }, { description = "Extracts return types using 'infer'" }),
    s("uniqarr", {
      t("const "),
      i(1, "uniqueArray"),
      t(" = Array.from(new Set("),
      i(2, "array"),
      t("));"),
    }, { description = "Creates an array with unique values from another array" }),
    s("mapobj", {
      t("const "),
      i(1, "newArray"),
      t(" = "),
      i(2, "array"),
      t(".map("),
      c(3, {
        sn(nil, { t("("), i(1, "item"), t(") => {"), t({ "", "\t" }), i(0), t({ "", "})" }) }),
        sn(nil, { t("async ("), i(1, "item"), t(") => {"), t({ "", "\t" }), i(0), t({ "", "})" }) }),
      }),
      t(";"),
    }, { description = "Maps over an array of objects" }),
    s("mapkv", {
      t("const "),
      i(1, "newObject"),
      t(" = Object.fromEntries("),
      t({ "", "\tObject.entries(" }),
      i(2, "originalObject"),
      t(").map((["),
      i(3, "key"),
      t(", "),
      i(4, "value"),
      t("]) => ["),
      rep(3),
      t(", "),
      i(0),
      t("])"),
      t({ "", ");" }),
    }, { description = "Maps over an object's key-value pairs" }),
    s("getkeyst", {
      t("const "),
      i(1, "keys"),
      t(": string[] = Object.keys("),
      i(2, "object"),
      t(");"),
    }, { description = "Retrieves keys from an object" }),
    s("getvaluest", {
      t("const "),
      i(1, "values"),
      t(": "),
      i(2, "ValueType"),
      t("[] = Object.values("),
      i(3, "object"),
      t(");"),
    }, { description = "Retrieves values from an object" }),
    s("clg", {
      t('console.log("'),
      i(1, "variable"),
      t(': ", '),
      rep(1),
      t(");"),
    }, { description = "Console log variable with label" }),
    s("exporttype", {
      t("export type "),
      i(1, "TypeName"),
      t(" = "),
      i(0),
      t(";"),
    }, { description = "Creates an exported type alias" }),
    s("readonlyprop", {
      t("readonly "),
      i(1, "propertyName"),
      t(": "),
      i(2, "Type"),
      t(";"),
    }, { description = "Adds a readonly property in a type/interface" }),
  },
  typescriptreact = {
    s("h1", {
      t("<h1>"),
      i(1),
      t("</h1>"),
    }),
    s("h2", {
      t("<h2>"),
      i(1),
      t("</h2>"),
    }),
    s("h3", {
      t("<h3>"),
      i(1),
      t("</h3>"),
    }),
    s("h4", {
      t("<h4>"),
      i(1),
      t("</h4>"),
    }),
    s("p", {
      t("<p>"),
      i(1),
      t("</p>"),
    }),
    s("div", {
      t("<div>"),
      i(1),
      t("</div>"),
    }),
    s("span", {
      t("<span>"),
      i(1),
      t("</span>"),
    }),
    s("ul", {
      t("<ul>"),
      i(1),
      t("</ul>"),
    }),
    s("li", {
      t("<li>"),
      i(1),
      t("</li>"),
    }),
    s("a", {
      t('<a href="'),
      i(1),
      t('">'),
      i(2),
      t("</a>"),
    }),
    s("img", {
      t('<img src="'),
      i(1),
      t('" alt="'),
      i(2),
      t('"/>'),
    }),
    s("form", {
      t("<form>"),
      i(1),
      t("</form>"),
    }),
    s("input", {
      t('<input type="'),
      i(1, "text"),
      t('" name="'),
      i(2),
      t('"/>'),
    }),
    s("button", {
      t("<button>"),
      i(1),
      t("</button>"),
    }),
    s("table", {
      t("<table>"),
      i(1),
      t("</table>"),
    }),
    s("tr", {
      t("<tr>"),
      i(1),
      t("</tr>"),
    }),
    s("td", {
      t("<td>"),
      i(1),
      t("</td>"),
    }),
    s("th", {
      t("<th>"),
      i(1),
      t("</th>"),
    }),
    s("section", {
      t("<section>"),
      i(1),
      t("</section>"),
    }),
    s("header", {
      t("<header>"),
      i(1),
      t("</header>"),
    }),
    s("footer", {
      t("<footer>"),
      i(1),
      t("</footer>"),
    }),
    s("nav", {
      t("<nav>"),
      i(1),
      t("</nav>"),
    }),
    s("anf", {
      t("("),
      i(1, "args"),
      t(") => "),
      i(0),
    }, { description = "Creates an arrow function" }),
    s("genf", {
      t("function "),
      i(1, "functionName"),
      t("<"),
      i(2, "T"),
      t(">("),
      i(3, "params: "),
      rep(2),
      t("): "),
      rep(2),
      t(" {"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates a generic function" }),
    s("typeguard", {
      t("function is"),
      i(1, "Type"),
      t("("),
      i(2, "obj"),
      t(": any): obj is "),
      rep(1),
      t(" {"),
      t({ "", "\treturn " }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates a type guard function" }),
    s("decorator", {
      t("@"),
      i(1, "DecoratorName"),
      t("("),
      i(2, "params"),
      t(")"),
      t({ "", "" }),
      i(0),
    }, { description = "Applies a decorator to a class or method" }),
    s("mapped", {
      t("type "),
      i(1, "NewType"),
      t(" = {"),
      t({ "", "\t[Key in keyof " }),
      i(2, "ExistingType"),
      t("]: "),
      i(3, "Type"),
      t({ "", "};" }),
    }, { description = "Creates a mapped type" }),
    s("condtype", {
      t("type "),
      i(1, "TypeName"),
      t(" = "),
      i(2, "Condition"),
      t(" extends "),
      i(3, "OtherType"),
      t(" ? "),
      i(4, "TrueType"),
      t(" : "),
      i(5, "FalseType"),
      t(";"),
    }, { description = "Defines a conditional type" }),
    s("moduleaug", {
      t("declare module '"),
      i(1, "moduleName"),
      t("' {"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Performs module augmentation" }),
    s("idxintf", {
      t("interface "),
      i(1, "InterfaceName"),
      t(" {"),
      t({ "", "\t[key: " }),
      i(2, "KeyType"),
      t("]: "),
      i(3, "ValueType"),
      t(";"),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Creates an interface with an index signature" }),
    s("curry", {
      t("const "),
      i(1, "curriedFunc"),
      t(" = ("),
      i(2, "param1: "),
      i(3, "Type1"),
      t(") => ("),
      i(4, "param2: "),
      i(5, "Type2"),
      t(") => "),
      i(0),
    }, { description = "Creates a curried function" }),
    s("hook", {
      t("function use"),
      i(1, "HookName"),
      t("() {"),
      t({ "", "\tconst [state, setState] = React.useState(" }),
      i(2, "initialState"),
      t(");"),
      t({ "", "\t" }),
      i(0),
      t({ "", "\treturn state;" }),
      t({ "", "}" }),
    }, { description = "Defines a custom React hook" }),
    s("union", {
      t("type "),
      i(1, "UnionName"),
      t(" = "),
      i(2, "Type1"),
      t(" | "),
      i(3, "Type2"),
      t(";"),
    }, { description = "Creates a union type" }),
    s("enum", {
      t("enum "),
      i(1, "EnumName"),
      t(" {"),
      t({ "", "\t" }),
      i(2, "Member1"),
      t(" = "),
      i(3, "Value1"),
      t(","),
      t({ "", "\t" }),
      i(0),
      t({ "", "}" }),
    }, { description = "Declares an enum" }),
    s("symbol", {
      t("const "),
      i(1, "sym"),
      t(" = Symbol('"),
      i(2, "description"),
      t("');"),
    }, { description = "Creates a unique symbol" }),
    s("tmpltype", {
      t("type "),
      i(1, "TypeName"),
      t(" = `"),
      i(2, "Prefix${"),
      i(3, "TypeVar"),
      t("}Suffix`"),
      t(";"),
    }, { description = "Defines a template literal type" }),
    s("keyremap", {
      t("type "),
      i(1, "RemappedType"),
      t(" = {"),
      t({ "", "\t[Key in keyof " }),
      i(2, "OriginalType"),
      t(" as "),
      i(3, "NewKey<Key>"),
      t("]: "),
      i(4, "ValueType"),
      t({ "", "};" }),
    }, { description = "Remaps keys in a mapped type" }),
    s("infer", {
      t("type "),
      i(1, "ReturnType"),
      t("<T> = T extends ("),
      i(2, "args"),
      t(") => infer R ? R : any;"),
    }, { description = "Extracts return types using 'infer'" }),
    s("uniqarr", {
      t("const "),
      i(1, "uniqueArray"),
      t(" = Array.from(new Set("),
      i(2, "array"),
      t("));"),
    }, { description = "Creates an array with unique values from another array" }),
    s("mapobj", {
      t("const "),
      i(1, "newArray"),
      t(" = "),
      i(2, "array"),
      t(".map("),
      c(3, {
        sn(nil, { t("("), i(1, "item"), t(") => {"), t({ "", "\t" }), i(0), t({ "", "})" }) }),
        sn(nil, { t("async ("), i(1, "item"), t(") => {"), t({ "", "\t" }), i(0), t({ "", "})" }) }),
      }),
      t(";"),
    }, { description = "Maps over an array of objects" }),
    s("mapkv", {
      t("const "),
      i(1, "newObject"),
      t(" = Object.fromEntries("),
      t({ "", "\tObject.entries(" }),
      i(2, "originalObject"),
      t(").map((["),
      i(3, "key"),
      t(", "),
      i(4, "value"),
      t("]) => ["),
      rep(3),
      t(", "),
      i(0),
      t("])"),
      t({ "", ");" }),
    }, { description = "Maps over an object's key-value pairs" }),
    s("getkeyst", {
      t("const "),
      i(1, "keys"),
      t(": string[] = Object.keys("),
      i(2, "object"),
      t(");"),
    }, { description = "Retrieves keys from an object" }),
    s("getvaluest", {
      t("const "),
      i(1, "values"),
      t(": "),
      i(2, "ValueType"),
      t("[] = Object.values("),
      i(3, "object"),
      t(");"),
    }, { description = "Retrieves values from an object" }),
    s("clg", {
      t('console.log("'),
      i(1, "variable"),
      t(': ", '),
      rep(1),
      t(");"),
    }, { description = "Console log variable with label" }),
    s("exporttype", {
      t("export type "),
      i(1, "TypeName"),
      t(" = "),
      i(0),
      t(";"),
    }, { description = "Creates an exported type alias" }),
    s("readonlyprop", {
      t("readonly "),
      i(1, "propertyName"),
      t(": "),
      i(2, "Type"),
      t(";"),
    }, { description = "Adds a readonly property in a type/interface" }),
  },
}
