local wk = require("which-key")

wk.add({
  { "<leader>a", "<cmd>lua require('harpoon.mark').add_file()<CR>", desc = "Add to Harpoon" },
  { "<leader>e", "<cmd>lua require('harpoon.ui').toggle_quick_menu()<CR>", desc = "Harpoon Menu" },
  { "<leader>h", "<cmd>lua require('harpoon.ui').nav_file(1)<CR>", desc = "Harpoon File 1" },
  { "<leader>t", "<cmd>lua require('harpoon.ui').nav_file(2)<CR>", desc = "Harpoon File 2" },
  { "<leader>n", "<cmd>lua require('harpoon.ui').nav_file(3)<CR>", desc = "Harpoon File 3" },
  { "<leader>m", "<cmd>lua require('harpoon.ui').nav_file(4)<CR>", desc = "Harpoon File 4" },
  { "<leader>u", "<cmd>UndotreeToggle<CR>", desc = "Undo Tree" },
  { "<leader>x", "/", desc = "Search in Document" },
  {
    "<leader>P",
    "<cmd>lua require('telescope.builtin').grep_string({ search = vim.fn.input('Grep For > ') })<CR>",
    desc = "Grep Finding",
  },
  { "<leader>f", "<cmd>lua require('telescope.builtin').git_files({ show_untracked = true })<CR>", desc = "Find Git Files" },
  { "<leader>F", "<cmd>lua find_all_files()<CR>", desc = "Find All Files" },
  { "<leader>c", group = "Code" },
  { "<leader>cf", "<cmd>lua require('conform').format({ async = true, lsp_fallback = true })<CR>", desc = "Format File" },
  { "<leader>ch", "<cmd>lua vim.lsp.buf.hover()<CR>", desc = "Hover Documentation" },
  { "<leader>ct", "<cmd>lua require('config.checkpoints').toggle()<CR>", desc = "Toggle Checkpoint" },
  { "<leader>cn", "<cmd>lua require('config.checkpoints').next()<CR>", desc = "Next Checkpoint" },
  { "<leader>cC", "<cmd>lua require('config.checkpoints').clear()<CR>", desc = "Clear Checkpoints" },
  { "<leader>g", group = "Git" },
  { "<leader>gg", "<cmd>LazyGit<CR>", desc = "LazyGit" },
  { "<leader>gb", "<cmd>GitBlameToggle<CR>", desc = "Toggle Git Blame" },
  { "<leader>o", group = "Open" },
  { "<leader>on", "<cmd>ProjectNotes<CR>", desc = "Project Notes" },
  { "<leader>ot", "<cmd>ProjectTerminalToggle<CR>", desc = "Project Terminal" },
  { "<leader>s", group = "Spell" },
  { "<leader>sn", "]s", desc = "Next Spell Error" },
  { "<leader>sp", "[s", desc = "Previous Spell Error" },
  { "<leader>sc", ":nohlsearch<CR>", desc = "Clear Highlight" },
  { "<leader>ss", "z=", desc = "Suggest Spelling" },
  { "<leader>z", "<C-w>w", desc = "Next Window" },
  { "<leader>k", "<cmd>CommentToggle<CR>", desc = "Toggle Comment" },
})
